version: 2
project_name: confpb
before:
  hooks:
    - make gen
    - make dependencies
builds:
  - id: protoc-gen-default
    main: ./cmd/protoc-gen-default
    binary: protoc-gen-default
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w -s -X github.com/marnixbouhuis/confpb/internal/version.GitReleaseTag={{.Tag}} -X github.com/marnixbouhuis/confpb/internal/version.ReleaseVersion={{.Version}} -X github.com/marnixbouhuis/confpb/internal/version.ShortCommit={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
  - id: protoc-gen-env
    main: ./cmd/protoc-gen-env
    binary: protoc-gen-env
    env:
      - CGO_ENABLED=0
    ldflags:
      - -w -s -X github.com/marnixbouhuis/confpb/internal/version.GitReleaseTag={{.Tag}} -X github.com/marnixbouhuis/confpb/internal/version.ReleaseVersion={{.Version}} -X github.com/marnixbouhuis/confpb/internal/version.ShortCommit={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
checksum:
  split: true
archives:
  - id: protoc-gen-default
    builds: [ "protoc-gen-default" ]
    format: tar.gz
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
  - id: protoc-gen-env
    builds: [ "protoc-gen-env" ]
    format: tar.gz
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
changelog:
  disable: true
release:
  mode: keep-existing # Keep existing release notes generated by release-drafter
